import express from 'express'
import Post from '../models/Post.js'
import Notification from '../models/Notification.js'
import { protect } from '../middleware/auth.js'
const router = express.Router()
router.get('/', protect, async (req, res, next) => { try { const page = Math.max(Number(req.query.page) || 1, 1); const limit = Math.min(Number(req.query.limit) || 12, 50); const posts = await Post.find().populate('user', 'username displayName profilePicture status').sort('-createdAt').skip((page - 1) * limit).limit(limit); res.json({ posts, page, hasMore: posts.length === limit }) } catch (e) { next(e) } })
router.post('/', protect, async (req, res, next) => { try { const { image, video, caption, game, tags = [], location } = req.body; if (!game || (!caption && !image && !video)) return res.status(400).json({ message: 'A game and some post content are required.' }); const post = await Post.create({ user: req.user.id, image, video, caption, game, tags, location }); await post.populate('user', 'username displayName profilePicture status'); res.status(201).json({ post }) } catch (e) { next(e) } })
router.get('/:id', protect, async (req, res, next) => { try { const post = await Post.findById(req.params.id).populate('user', 'username displayName profilePicture status').populate('comments.user', 'username profilePicture'); if (!post) return res.status(404).json({ message: 'Post not found.' }); res.json({ post }) } catch (e) { next(e) } })
router.delete('/:id', protect, async (req, res, next) => { try { const post = await Post.findOneAndDelete({ _id: req.params.id, user: req.user.id }); if (!post) return res.status(404).json({ message: 'Post not found or not owned by you.' }); res.status(204).end() } catch (e) { next(e) } })
router.post('/:id/like', protect, async (req, res, next) => { try { const post = await Post.findById(req.params.id); if (!post) return res.status(404).json({ message: 'Post not found.' }); const liked = post.likes.some((id) => id.equals(req.user._id)); if (liked) post.likes.pull(req.user._id); else { post.likes.push(req.user._id); if (!post.user.equals(req.user._id)) await Notification.create({ recipient: post.user, sender: req.user._id, type: 'like', referenceId: post._id }) } await post.save(); res.json({ liked: !liked, likeCount: post.likes.length }) } catch (e) { next(e) } })
router.post('/:id/comments', protect, async (req, res, next) => { try { const { text } = req.body; if (!text?.trim()) return res.status(400).json({ message: 'Comment cannot be empty.' }); const post = await Post.findById(req.params.id); if (!post) return res.status(404).json({ message: 'Post not found.' }); post.comments.push({ user: req.user.id, text: text.trim() }); await post.save(); if (!post.user.equals(req.user._id)) await Notification.create({ recipient: post.user, sender: req.user._id, type: 'comment', referenceId: post._id }); const comment = post.comments.at(-1); await comment.populate('user', 'username profilePicture'); res.status(201).json({ comment }) } catch (e) { next(e) } })
export default router
