import express from 'express'
import Squad from '../models/Squad.js'
import { protect } from '../middleware/auth.js'
const router = express.Router()
router.get('/', protect, async (req, res, next) => { try { const filter = {}; if (req.query.game) filter.game = req.query.game; const squads = await Squad.find(filter).populate('owner', 'username profilePicture status').populate('members.user', 'username profilePicture status skillLevel').sort('-createdAt'); res.json({ squads }) } catch (e) { next(e) } })
router.post('/', protect, async (req, res, next) => { try { const { name, game, description, maxMembers, skillLevel, roles, platform, voiceChat, playTime, banner } = req.body; if (!name || !game || !description) return res.status(400).json({ message: 'Name, game and description are required.' }); const squad = await Squad.create({ name, game, description, maxMembers, skillLevel, roles, platform, voiceChat, playTime, banner, owner: req.user.id, members: [{ user: req.user.id, role: roles?.[0] || 'Leader' }] }); await squad.populate('owner', 'username profilePicture status'); res.status(201).json({ squad }) } catch (e) { next(e) } })
router.get('/:id', protect, async (req, res, next) => { try { const squad = await Squad.findById(req.params.id).populate('owner', 'username profilePicture status').populate('members.user', 'username profilePicture status skillLevel'); if (!squad) return res.status(404).json({ message: 'Squad not found.' }); res.json({ squad }) } catch (e) { next(e) } })
router.post('/:id/join', protect, async (req, res, next) => { try { const squad = await Squad.findById(req.params.id); if (!squad) return res.status(404).json({ message: 'Squad not found.' }); if (squad.members.length >= squad.maxMembers) return res.status(400).json({ message: 'This squad is full.' }); if (!squad.members.some((m) => m.user.equals(req.user._id))) { squad.members.push({ user: req.user.id, role: 'Member' }); await squad.save() }; res.json({ joined: true }) } catch (e) { next(e) } })
router.post('/:id/invite', protect, async (req, res) => res.status(501).json({ message: 'Squad invitations are ready for a notification delivery provider.' }))
export default router
